artifacts_root: artifacts
# In order to avoid the path problems
data_ingestion:
    root_dir: artifacts/data_ingestion
    source_url: https://github.com/Emanalytics7/Data-Storage/raw/main/data.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion

prepare_base_model:
    root_dir: artifacts/prepare_base_model
    base_model_path: artifacts/prepare_base_model/base_model.h5
    updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5


prepare_callbacks:
    root_dir: artifacts/prepare_callbacks
    tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
    checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5